CREATE TABLE app_user
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    password_salt VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE file
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename  VARCHAR(255)                            NOT NULL,
    file_type VARCHAR(255)                            NOT NULL,
    size      BIGINT                                  NOT NULL,
    data      OID                                     NOT NULL,
    post_id   BIGINT,
    CONSTRAINT pk_file PRIMARY KEY (id)
);

CREATE TABLE post
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content     VARCHAR(255)                            NOT NULL,
    posted_on   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    app_user_id BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

ALTER TABLE file
    ADD CONSTRAINT FK_FILE_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_APP_USER FOREIGN KEY (app_user_id) REFERENCES app_user (id);