CREATE TABLE post_mention
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_user_id        BIGINT,
    post_id            BIGINT,
    mentioned_username VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_post_mention PRIMARY KEY (id)
);

ALTER TABLE post_mention
    ADD CONSTRAINT FK_POST_MENTION_ON_APP_USER FOREIGN KEY (app_user_id) REFERENCES app_user (id);

ALTER TABLE post_mention
    ADD CONSTRAINT FK_POST_MENTION_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE app_user
    ALTER COLUMN email SET NOT NULL;